FROM chuanwen/cowsay:latest
ENTRYPOINT [ "/usr/games/cowsay" ]
CMD ["Tome a vacina!"]

# Para obter a lista com os outros animais, rode o comando: docker container run cowsay -l
# Para passar um parâmetro logo após o comando: docker container run cowsay Xô coronga
# Mudar para um leão: docker container run cowsay -f moofasa "Tome a vacina!"